// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// CellSize is an autogenerated mock type for the CellSize type
type CellSize struct {
	mock.Mock
}

// NewCellSize creates a new instance of CellSize. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewCellSize(t testing.TB) *CellSize {
	mock := &CellSize{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
