// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	wlinterpreter "github.com/dmalykh/wlinterpreter"
)

// ExecuteFunc is an autogenerated mock type for the ExecuteFunc type
type ExecuteFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: i
func (_m *ExecuteFunc) Execute(i wlinterpreter.Interpreter) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(wlinterpreter.Interpreter) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExecuteFunc creates a new instance of ExecuteFunc. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewExecuteFunc(t testing.TB) *ExecuteFunc {
	mock := &ExecuteFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
